name: Netlify Deploy Preview

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Change this to the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Change this if you have a different build script

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          deploy_output=$(netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir dist --message "Deploy preview for PR ${{ github.event.number }}" --alias "pr-${{ github.event.number }}" --json)
          deploy_url=$(echo $deploy_output | jq -r '.deploy_url')
          echo "deploy_url=${deploy_url}" >> $GITHUB_ENV

      - name: Post deploy URL to PR
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const url = process.env.deploy_url;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The deploy preview is ready: ${url}`
            });